# Generated by Django 3.1.4 on 2020-12-24 08:08

from django.db import migrations, models
import django_drf_filepond.models


class Migration(migrations.Migration):

    dependencies = [
        ('django_drf_filepond', '0009_temporaryuploadchunked_offset_utime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporaryupload',
            name='file',
            field=models.FileField(storage=django_drf_filepond.models.FilePondLocalStoredStorage(), upload_to=django_drf_filepond.models.get_upload_path),
        ),
    ]
